# Generated by Django 4.0.4 on 2022-05-11 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingPartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=200)),
                ('workingPart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.workingpart')),
            ],
        ),
        migrations.AddField(
            model_name='workingpart',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.workingscope'),
        ),
        migrations.CreateModel(
            name='MarketingMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('subject', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('status', models.CharField(choices=[('C ', 'Canceled'), ('D', 'Done'), ('P', 'Pending'), ('S', 'Shifted')], max_length=40)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
                ('meeting_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.meetingtype')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('statement', models.TextField()),
                ('price_in_numbers', models.IntegerField()),
                ('total_area', models.IntegerField()),
                ('total_time_period', models.IntegerField()),
                ('gregorian_date', models.DateTimeField(auto_now_add=True)),
                ('contract_subject', models.TextField()),
                ('additional_details', models.TextField()),
                ('municipal_confirmed', models.BooleanField()),
                ('is_approval', models.BooleanField(default=False)),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.contracttype')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partName', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.projectcomponent')),
            ],
        ),
    ]
