# Generated by Django 4.0.4 on 2022-05-11 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceOfferType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_offer_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PriceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_in_letters', models.CharField(max_length=100)),
                ('price_in_numbers', models.FloatField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.contract')),
                ('price_offer_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.priceoffertype')),
            ],
        ),
    ]
