# Generated by Django 4.0.4 on 2022-05-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_priceoffertype_priceoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='total_time_period',
            field=models.DurationField(),
        ),
    ]
