# Generated by Django 4.0.4 on 2022-05-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_contract_total_time_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='total_time_period',
            field=models.DurationField(help_text='Expects data in the format "DD HH:MM:SS ex: 4 12:00:00'),
        ),
    ]
