# Generated by Django 4.0.4 on 2022-05-11 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_design', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoodBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MoodBoardPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('mood_board_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineering.moodboard')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_project', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StyleMoodBoardPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('creation_time', models.FloatField()),
                ('modification_time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_windows', models.IntegerField()),
                ('project_issue_date', models.DateField(auto_now_add=True)),
                ('project_due_date', models.DateField()),
                ('municipal_confirmed', models.BooleanField()),
                ('customer_finishing_confirm', models.BooleanField(default=False)),
                ('customer_notes', models.TextField()),
                ('current_progress', models.FloatField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.contract')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineering.projecttype')),
            ],
        ),
        migrations.CreateModel(
            name='MoodBoardPartImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('image_note', models.CharField(max_length=200)),
                ('mood_board_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='engineering.moodboardpart')),
            ],
        ),
        migrations.AddField(
            model_name='moodboardpart',
            name='mood_board_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineering.stylemoodboardpart'),
        ),
        migrations.AddField(
            model_name='moodboardpart',
            name='table_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineering.tableitem'),
        ),
        migrations.AddField(
            model_name='moodboard',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineering.project'),
        ),
        migrations.AddField(
            model_name='moodboard',
            name='type_of_design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineering.designtype'),
        ),
    ]
